import esbuild from "esbuild";
import process from "node:process";
import { existsSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import builtins from "builtin-modules";

const require = createRequire(import.meta.url);
const prod = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
paper.college Obsidian plugin
*/
`;

function pdfWorkerPath() {
  const pdfjsEntry = require.resolve("pdfjs-dist/package.json");
  const candidates = [
    join(dirname(pdfjsEntry), "build", "pdf.worker.mjs"),
    join(dirname(pdfjsEntry), "legacy", "build", "pdf.worker.mjs"),
  ];
  const worker = candidates.find((path) => existsSync(path));
  if (!worker) {
    throw new Error("pdfjs-dist worker source not found");
  }
  return worker;
}

// Community-directory installs receive only main.js, manifest.json and
// styles.css, so the worker has to travel inside main.js as a string.
const pdfWorkerSourcePlugin = {
  name: "pdfjs-worker-source",
  setup(build) {
    // esbuild writes the resolved path into main.js as a comment, so this stays
    // a fixed label instead of an absolute path that differs per machine.
    build.onResolve({ filter: /^pdfjs-worker-source$/ }, () => ({
      path: "pdfjs-dist/build/pdf.worker.mjs",
      namespace: "pdfjs-worker-source",
      pluginData: { file: pdfWorkerPath() },
    }));
    build.onLoad(
      { filter: /.*/, namespace: "pdfjs-worker-source" },
      (args) => ({
        contents: readFileSync(args.pluginData.file, "utf8"),
        loader: "text",
      }),
    );
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  plugins: [pdfWorkerSourcePlugin],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
